---
title: "lab-testes-hipotese"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(lubridate)
install.packages("perm")
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))
```

Vendo a distribuição dos dados
```{r}
agrupado_por_grupos <- buscas %>%
    group_by(group) %>% 
    summarise(media_click = mean(num_clicks)) 
    
agrupado_por_grupos %>%
    ggplot(aes(x = group, y = media_click)) + 
    geom_point() 
```

## Com teste de hipótese

```{r}
library(perm)

grupo_a = buscas %>% filter(group == "a") %>% pull(num_clicks)
grupo_b = buscas %>% filter(group == "b") %>% pull(num_clicks)
    
permTS(grupo_a, grupo_b)
```

## Com IC
```{r}
theta_embaralhado = function(d, i){
    buscas2 = d %>% 
         slice(i) %>% 
        group_by(group) %>% 
        summarise(media = mean(num_clicks)) 
    
    grupo_a = buscas2 %>% filter(group == "a") %>% pull(media)
    grupo_b = buscas2 %>% filter(group == "b") %>% pull(media)
    
    grupo_a - grupo_b
}

theta_embaralhado(buscas, 1:NROW(buscas))
```


```{r}
library(boot)
library(broom)
buscas %>% 
    boot(statistic = theta_embaralhado, R = 2000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```


# 2. A diferença na proporção buscas com zero resultados nos grupos A e B

Criando a coluna de é busca "eh_zero"
```{r}
buscas_com_results_zero <- buscas %>%
    mutate(eh_resultado_zero = results == 0) 
```

# Vendo a diferença na amostra
```{r}
group_a = buscas_com_results_zero  %>% group_by(group) %>% summarise(prop_zero = sum(eh_resultado_zero)/n()) %>% filter(group == "a") %>% pull(prop_zero)
group_b = buscas_com_results_zero  %>% group_by(group) %>% summarise(prop_zero = sum(eh_resultado_zero)/n()) %>% filter(group == "b") %>% pull(prop_zero)


theta_geral = group_a - group_b

theta_geral
```

## Com teste de hipótese

```{r}
theta_embaralhado = function(d){
    embaralhados = d %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(prop = sum(eh_resultado_zero)/n()) 
    
    grupo_a = embaralhados %>% filter(grupo_embaralhado == "a") %>% pull(prop)
    grupo_b = embaralhados %>% filter(grupo_embaralhado == "b") %>% pull(prop)
    
    grupo_a - grupo_b
}
theta_embaralhado(buscas_com_results_zero)
```

```{r}
diffs1 = replicate(2000, {theta_embaralhado(buscas_com_results_zero)})
tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") + 
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_vline(xintercept = - theta_diff_rate(buscas.por.sessao, 1:NROW(buscas.por.sessao)), 
             color = "orange") + 
    geom_rug()

```

```{r}
mean(abs(diffs1) >= abs(theta_embaralhado2(buscas_com_results_zero, 1:NROW(buscas))))
```


## Com IC
```{r}
theta_embaralhado2 = function(d, i){
    buscas2 = d %>% 
         slice(i) %>% 
        group_by(group) %>% 
        summarise(prop = sum(eh_resultado_zero)/n()) 
    
    grupo_a = buscas2 %>% filter(group == "a") %>% pull(prop)
    grupo_b = buscas2 %>% filter(group == "b") %>% pull(prop)
    
    grupo_a - grupo_b
}

theta_embaralhado2(buscas_com_results_zero, 1:NROW(buscas))
```


```{r}
library(boot)
library(broom)
buscas_com_results_zero %>% 
    boot(statistic = theta_embaralhado, R = 2000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```